# Generated by Django 4.0.6 on 2022-07-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImputDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Keyboard', 'keyboard'), ('Mouse', 'Mouse'), ('Display', 'Display'), ('Speaker', 'Speaker'), ('Motherboard', 'Motherboard'), ('Processor', 'Processor')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Keyboard', 'keyboard'), ('Mouse', 'Mouse'), ('Display', 'Display'), ('Speaker', 'Speaker'), ('Motherboard', 'Motherboard'), ('Processor', 'Processor')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Keyboard', 'keyboard'), ('Mouse', 'Mouse'), ('Display', 'Display'), ('Speaker', 'Speaker'), ('Motherboard', 'Motherboard'), ('Processor', 'Processor')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('outputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.outputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('order.outputdevice',),
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('imputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.imputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('order.imputdevice',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('internaldevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.internaldevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('order.internaldevice',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('imputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.imputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('order.imputdevice',),
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('internaldevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.internaldevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('order.internaldevice',),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('outputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.outputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('order.outputdevice',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.computer')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.display'),
        ),
        migrations.AddField(
            model_name='computer',
            name='keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.keyboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.motherboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.mouse'),
        ),
        migrations.AddField(
            model_name='computer',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.processor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.speaker'),
        ),
    ]
