# Generated by Django 4.0.6 on 2022-07-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='computers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('computer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.computer')),
                ('orden', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
