# Generated by Django 4.0.6 on 2022-07-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_code_orderdetails_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
